### ISSUE TITLE
Add support for tags

### ISSUE THREAD

**Issue by nadgowdas** [IBM/gauge#3]
**Is your feature request related to a problem? Please describe.**
while running `gauge` against `colors.js` repo, discovered that projects might just `tag` the releases on GitHub source, but not create an explicit `release`. So, add a support for discovering these `tags`.

**Describe the solution you'd like**
Support discoverability of releases through `tags`. Also, need to make differentiate release tags vs operational tags. 

**Additional context**
When ran against `colors.js` repo, with additional debug statements:
```
./gauge package -p colors -e Node -t v1.3.3 -r https://github.com/Marak/colors.js
err GET https://api.github.com/repos/Marak/colors.js/releases/latest: 404 Not Found []
```

**Comment by leec94** [comment]
This repo will be archived so closing out all issues.
